import { useState } from "react";
import { Navigate } from "react-router";
import { Package, Search, Plus, Edit2, Trash2 } from "lucide-react";
import { useApp } from "../../context/AppContext";
import { Modal, ConfirmModal } from "../../components/ui/Modal";
import { Badge } from "../../components/ui/Badge";
import { EmptyState } from "../../components/ui/EmptyState";
import type { InvimaProduct } from "../../types";
import { toast } from "sonner";
import { useAuth } from "../../context/AuthContext";
import { EMPRESAS } from "../../constants";

const emptyMaterial = (): Omit<InvimaProduct, "id"> => ({ codigoMaterial: "", productName: "", clase: "PT", codigo: "", registryNumber: "", controlado: false, empresa: "Humax", empresaCode: "CO11", holder: "Humax", fabricante: "", estatusSap: "Activo", canal: "", tipoMedicamento: "", presentacion: "", internalStatus: "", requiereSap: true, requiereInvima: true });

export default function InvimaPage() {
  const { user } = useAuth();
  const { invimaProducts, addInvimaProduct, updateInvimaProduct, deleteInvimaProduct } = useApp();
  const [search, setSearch] = useState(""); const [empresaFilter, setEmpresaFilter] = useState("");
  const [modalOpen, setModalOpen] = useState(false); const [editItem, setEditItem] = useState<InvimaProduct | null>(null); const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);
  const [form, setForm] = useState<Omit<InvimaProduct, "id">>(emptyMaterial());
  if (user?.rol !== "planeacion") return <Navigate to="/dashboard" replace />;
  const filtered = invimaProducts.filter((p) => { const q = search.toLowerCase().trim(); return (!empresaFilter || p.empresa === empresaFilter) && (!q || [p.codigo || "", p.registryNumber || "", p.productName || ""].some((value) => value.toLowerCase().includes(q))); });
  const openCreate = () => { setEditItem(null); setForm(emptyMaterial()); setModalOpen(true); };
  const openEdit = (item: InvimaProduct) => { setEditItem(item); setForm({ ...emptyMaterial(), ...item, clase: item.clase || "PT", codigoMaterial: item.codigoMaterial || "" }); setModalOpen(true); };
  const handleSave = () => { if (!form.codigoMaterial?.trim() || !form.productName.trim() || !form.codigo?.trim() || !form.registryNumber.trim()) { toast.error("Código de material, texto breve, código SAP e INVIMA son obligatorios"); return; } if (editItem) { updateInvimaProduct(editItem.id, form); toast.success("Material actualizado"); } else { addInvimaProduct(form); toast.success("Material creado"); } setModalOpen(false); };
  return <div className="space-y-5">
    <div className="flex items-center justify-between"><div><h1 className="text-xl font-bold text-slate-900">Maestro de Materiales</h1><p className="mt-0.5 text-sm text-slate-500">{filtered.length} registros</p></div><button onClick={openCreate} className="flex items-center gap-2 rounded-lg bg-blue-700 px-4 py-2 text-sm font-medium text-white hover:bg-blue-800"><Plus size={16} /> Nuevo material</button></div>
    <div className="flex flex-wrap gap-3"><div className="relative min-w-48 flex-1"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por código SAP, INVIMA o nombre..." className="w-full rounded-lg border border-slate-300 py-2 pl-8 pr-4 text-sm" /></div><select value={empresaFilter} onChange={(e) => setEmpresaFilter(e.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">Todas las empresas</option>{EMPRESAS.map((empresa) => <option key={empresa}>{empresa}</option>)}</select></div>
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white">{filtered.length === 0 ? <EmptyState icon={<Package size={48} />} title="No se encontraron materiales" /> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-slate-200 bg-slate-50"><Head>Código material</Head><Head>Texto breve</Head><Head>Tipo</Head><Head>Código SAP</Head><Head>INVIMA</Head><Head>Condición</Head><th /></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((p) => <tr key={p.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-mono text-xs text-slate-700">{p.codigoMaterial || "—"}</td><td className="px-4 py-3 font-medium text-slate-800">{p.productName}</td><td className="px-4 py-3"><Badge label={p.clase || "—"} variant="muted" /></td><td className="px-4 py-3 font-mono text-xs font-semibold text-blue-700">{p.codigo}</td><td className="px-4 py-3 font-mono text-xs text-slate-700">{p.registryNumber}</td><td className="px-4 py-3"><Badge label={p.controlado ? "Controlado" : "No controlado"} variant={p.controlado ? "error" : "success"} /></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><button onClick={() => openEdit(p)} className="rounded p-1.5 text-slate-400 hover:bg-blue-50 hover:text-blue-600"><Edit2 size={14} /></button><button onClick={() => setDeleteConfirm(p.id)} className="rounded p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={14} /></button></div></td></tr>)}</tbody></table></div>}</div>
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title={editItem ? "Editar material" : "Nuevo material"} size="lg" footer={<><button onClick={() => setModalOpen(false)} className="rounded-lg px-4 py-2 text-sm text-slate-600 hover:bg-slate-100">Cancelar</button><button onClick={handleSave} className="rounded-lg bg-blue-700 px-5 py-2 text-sm font-semibold text-white hover:bg-blue-800">Guardar</button></>}><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="Código de material *"><input value={form.codigoMaterial || ""} onChange={(e) => setForm((p) => ({ ...p, codigoMaterial: e.target.value }))} /></Field><Field label="Tipo de material *"><select value={form.clase || "PT"} onChange={(e) => setForm((p) => ({ ...p, clase: e.target.value }))}><option value="MP">ROH — Materia prima (MP)</option><option value="ME">ME — Material de empaque</option><option value="PT">FERT — Producto terminado (PT)</option><option value="ST">HALB — Semielaborado (ST)</option><option value="UNBW">UNBW — Material de laboratorio</option></select></Field><Field label="Texto breve *" wide><input value={form.productName} onChange={(e) => setForm((p) => ({ ...p, productName: e.target.value }))} placeholder="Nombre, presentación, concentración..." /></Field><Field label="Código SAP *"><input value={form.codigo || ""} onChange={(e) => setForm((p) => ({ ...p, codigo: e.target.value }))} /></Field><Field label="Código INVIMA *"><input value={form.registryNumber} onChange={(e) => setForm((p) => ({ ...p, registryNumber: e.target.value }))} /></Field><Field label="Condición *" wide><select value={form.controlado ? "controlado" : "no_controlado"} onChange={(e) => setForm((p) => ({ ...p, controlado: e.target.value === "controlado" }))}><option value="no_controlado">No controlado</option><option value="controlado">Controlado</option></select></Field></div></Modal>
    <ConfirmModal open={!!deleteConfirm} onClose={() => setDeleteConfirm(null)} onConfirm={() => { if (deleteConfirm) { deleteInvimaProduct(deleteConfirm); toast.success("Material eliminado"); setDeleteConfirm(null); } }} title="Eliminar material" message="¿Está seguro de eliminar este material?" confirmLabel="Eliminar" danger />
  </div>;
}
function Head({ children }: { children: React.ReactNode }) { return <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{children}</th>; }
function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) { return <div className={wide ? "sm:col-span-2" : ""}><label className="mb-1 block text-sm font-medium text-slate-700">{label}</label><div className="[&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-slate-300 [&_input]:px-3 [&_input]:py-2 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:border-slate-300 [&_select]:bg-white [&_select]:px-3 [&_select]:py-2">{children}</div></div>; }
